TARGET          ?= stm32f4-discovery

LIBNAME         ?= opencm3_stm32f4
DEFS            ?= -DSTM32F4
DEFS            += -DSTD_CON=USART2
DEFS            += -DMST_SIZE=0x400

FP_FLAGS        ?= -mfloat-abi=hard -mfpu=fpv4-sp-d16
ARCH_FLAGS      ?= -mthumb -mcpu=cortex-m4 $(FP_FLAGS) 

OOCD            ?= openocd
OOCD_INTERFACE  ?= stlink-v2
OOCD_BOARD      ?= stm32f4discovery

objs            += board_setup.o
objs            += stubs.o stm32_con.o
aobjs           += helloworld.o